- id: towncrier-draft
  name: towncrier build --draft
  description: Check towncrier changelog updates
  language: python
  entry: towncrier build --draft
  pass_filenames: false
  types: [text]

- id: towncrier-checks
  name: towncrier check
  description: Check for missing news fragments
  language: python
  entry: towncrier check
  pass_filenames: false
  stages:
    - pre-push
  always_run: true

- id: towncrier-update
  name: towncrier build
  description: Update changelog with towncrier
  language: python
  entry: towncrier build --yes
  pass_filenames: false
  always_run: true
  stages:
    - manual
