version: 2

sphinx:
  # We want to fail as this is also our CI check for the docs.
  fail_on_warning: True

# We don't need PDF and epub for the docs.
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  system_packages: False
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
